version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: userService
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbHotel
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"